name: Build and Release Foundry VTT Module

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update module.json version
        run: |
          VERSION=$(date +'%Y.%m.%d.%H%M')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          jq --arg ver "$VERSION" '.version = $ver' module.json > tmp.$$.json && mv tmp.$$.json module.json

      - name: Install zip
        run: sudo apt-get install zip -y

      - name: Create zip file
        run: zip -r pathfinder-timeline.zip . -x .git/\* \*.github/workflows/\*

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release ${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pathfinder-timeline.zip
          asset_name: pathfinder-timeline.zip
          asset_content_type: application/zip

      - name: Update module.json with URLs
        run: |
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/pathfinder-timeline.zip"
          MANIFEST_URL="https://raw.githubusercontent.com/${{ github.repository }}/main/module.json"
          jq --arg download_url "$DOWNLOAD_URL" --arg manifest_url "$MANIFEST_URL" '.download = $download_url | .manifest = $manifest_url' module.json > tmp.$$.json && mv tmp.$$.json module.json

      - name: Commit updated module.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add module.json
          git commit -m "Update module.json with manifest and download URLs"
          git push origin main
